Models/Contact.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;

namespace Abbas_Rahimzadeh_Dotnet.Models
{
    public class Contact
    {
        [Required]
        [Key]
        public int Id {get;set;}

        [Required]
        [StringLength(255)]
        public string date {get;set;}
        
    }
}

Models/ContextDBS.cs
using Microsoft.EntityFrameworkCore;

namespace Abbas_Rahimzadeh_Dotnet.Models
{
    public class ContextDBS:DbContext
    {
        public ContextDBS(DbContextOptions<ContextDBS> options):base(options)
        {

        }
        public DbSet<Users> Users { get; set; }
        public DbSet<Products> Products { get; set; }
        public DbSet<Contact> Cantact { get; set; }
        public DbSet<Order> Order { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace Abbas_Rahimzadeh_Dotnet.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
} 

Models/Order.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Abbas_Rahimzadeh_Dotnet.Models
{
    public class Order
    {
        [Required]
        [Key]
        public int Id {get;set;}
    }
}

Models/Products.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations.Schema;

namespace Abbas_Rahimzadeh_Dotnet.Models
{
    public class Products
    {
        [Required]
        [Key]
        public int Id {get;set;}


        [Required]
        [StringLength(255)]
        public string picPath {get;set;}

        [NotMapped]
        public IFormFile pic { get; set; }

        [Required]
        [StringLength(255)]
        public string? title {get;set;}


        [StringLength(255)]
        public string? price {get;set;}

        [StringLength(255)]
        public string? offPrice {get;set;}


        [StringLength(255)]
        public string? count {get;set;}



        [StringLength(255)]
        public string? description {get;set;}

        public ICollection<Order> Orders { get; set; }
    }
}

Models/Users.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using DNTPersianUtils.Core;
using MD.PersianDateTime;

namespace Abbas_Rahimzadeh_Dotnet.Models
{
    public class Users
    {
        private string birthday;
        [Required]
        [Key]
        public int Id {get;set;}
        [StringLength(255)]
        public string? Name {get;set;}

        [StringLength(255)]
        public string Email {get;set;}
        
        [StringLength(255)]
        [Required]
        public string Password {get;set;}

        [StringLength(255)]
        [Required]
        public string Birthday {
            get{
                var date = birthday.ToGregorianDateOnly();
                return date.ToString();
            }
            set{
                birthday = value;
            }
        }


    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Abbas_Rahimzadeh_Dotnet.Models;


namespace Abbas_Rahimzadeh_Dotnet.Controllers;

public class HomeController : Controller
{
    private readonly ContextDBS db;
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger, ContextDBS contextDBS)
    {
        db = contextDBS;
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult SaveUser(Users user){
        db.Users.Add(user);
        db.SaveChanges();
        return RedirectToAction("ContactUs");
    }

    public IActionResult ContactUs()
    {

        var query = db.Users.ToList().OrderByDescending(user => user.Id);

        ViewBag.countUser = db.Users.ToList().Count;

        // double sumAllWeight = 0;
        // foreach(var item in query){
        //     if (item.Weight.HasValue)
        //     sumAllWeight += item.Weight.Value;
        // }

        return View(query);
    }
  
    public IActionResult AboutUs()
    {
        return View();
    }
    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/ShoppingController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Abbas_Rahimzadeh_Dotnet.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace Abbas_Rahimzadeh_Dotnet.Controllers
{
    [Route("[controller]")]
    public class ShoppingController : Controller
    {
        private readonly ContextDBS db; 
        private readonly ILogger<ShoppingController> _logger;

        private readonly IWebHostEnvironment webHostEnvironment;

        public ShoppingController(ILogger<ShoppingController> logger, ContextDBS contextDBS, IWebHostEnvironment webHostEnvironment)
        {
            _logger = logger;
            this.webHostEnvironment = webHostEnvironment;
            this.db = contextDBS;
        }
        [HttpGet("/Shopping")]
        public IActionResult Index()
        {
            
            var query = db.Products.ToList();
            return View(query);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
        [HttpPost("/Shopping")]
        public IActionResult SaveForms(Products products){
            string UniqueFileName = Guid.NewGuid() + products.pic.FileName;
            string UploadFolder = Path.Combine(webHostEnvironment.WebRootPath + "\\Images", UniqueFileName);
            using (FileStream fs = new FileStream(UploadFolder, FileMode.Create)){
                products.pic.CopyTo(fs);
            };
            products.picPath = "/Images/" + UniqueFileName;
            db.Products.Add(products);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Views/Home/AboutUs.cshtml
@{
    ViewData["Title"] = "AboutUs";
}
<h1>درباره ما</h1>
<p>امیر جلوداریان هستم</p> 

Views/Home/ContactUs.cshtml
@model IEnumerable<Users>
@{
    ViewData["Title"] = "ContactUs";
}
<form asp-controller="Home" asp-action="SaveUser" method="post">
    <input type="text" placeholder="نام" name="Name" />
    <input type="email" placeholder="ایمیل" name="Email" />
    <input type="password" placeholder="رمز" name="Password" />
    <input class="sample-date-picker bg-white w-100 p-3" style="width: 170px !important;height: 34px;border: 1px solid black;border-radius: 3px;" name="Birthday" placeholder="تاریخ" type="text" id="date">
    <input type="submit" class="btn btn-primary" value="ذخیره" />
</form>
<table class="table table-responsive">
<h5>Count Of Users: @ViewBag.countUser</h5>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Email</th>
                <th>Birthday</th>
                <th>Password</th>
            </tr>
            @foreach(var item in Model){
                    <tr>
                        <td>@item.Id</td>
                        <td>@item.Name</td>
                        <td>@item.Email</td>
                        <td>@item.Birthday</td>
                        <td>@item.Password</td>
                    </tr>
                
            }
</table>
<h1>تماس به ما</h1>
<p>09191234567</p>

  
     

   

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div> 

Views/Home/Shop.cshtml
@{
    ViewData["Title"] = "Shop";
}
<h1>فروشگاه</h1>
<p>محصولات</p> 

@* @using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
     <p class="form-horizontal">
        <p>Employee</p>
        <hr />
        
        <p class="form-group">
        
            <p class="col-md-10">
        
            </p>
        </p>

    
        <p class="form-group">
            <p class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </p>
        </p>
    </p>
}

} *@
<table class="table table-responsive">
            <tr>
                <th>Id</th>
                <th>Image</th>
                <th>Title</th>
                <th>Price</th>
                <th>Count</th>
                <th>Desc</th>
            </tr>
            @{
                foreach(var item in Model){
                    <tr>
                        <td>@item.Id</td>
                        <td><img src="@item.picPath" /></td>
                        <td>@item.title</td>
                        <td>@item.price</td>
                        <td>@item.count</td>
                        <td>@item.description</td>
                    </tr>
                }
            }
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Abbas Rahimzadeh</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Abbas_Rahimzadeh_Dotnet.styles.css" asp-append-version="true" />
    
    <link type="text/css" rel="stylesheet" href="https://cdn.jsdelivr.net/gh/rastikerdar/vazirmatn@v33.003/Vazirmatn-font-face.css"/> 
    <link type="text/css" rel="stylesheet" href="~/lib/mpdatepicker/dist/jquery.mpdatepicker.min.css"/>
</head>
<body>
    <header> 
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Abbas Rahimzadeh</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">خانه</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">قوانین</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="ContactUs">تماس با ما</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Shopping" asp-action="Index">فروشگاه</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="AboutUs">درباره ما</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - امیر جلوداریان - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script type="text/javascript" src="~/lib/mpdatepicker/dist/jquery.mpdatepicker.min.js"></script>
    <script>
        $(function () {
            $(".sample-date-picker").mpdatepicker({
                'timePicker': true,
                onOpen: function () {
                    console.log('open');
                },
                onSelect: function (selected) {
                    console.log('select', selected);
                },
                onChange: function (oldVal, newVal) {
                    console.log('change', oldVal, newVal);
                },
                onClose: function () {
                    console.log('close');
                },
            });
            
        });
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shopping/index.cshtml
@model IEnumerable<Abbas_Rahimzadeh_Dotnet.Models.Products>
@{
    ViewData["Title"] = "Shop";
}
<h1>فروشگاه</h1>
<p>محصولات</p> 

<form asp-action="SaveForms" asp-controller="Shopping" method="post" enctype="multipart/form-data" class="create-product-form">
    <h6>اضافه کردن محصول</h6>
    <hr />
    <input type="text" name="title" placeholder="Title" />
    <input type="number" name="price" placeholder="Price" />
    <input type="number" name="offPrice" placeholder="Off Price" />
    <input type="text" name="count" placeholder="Count" />
    <input type="text" name="description" placeholder="Desc" />
    <hr />
    <input type="file" class="file-form-input" name="pic" placeholder="Pic" />
    <br />
    <input type="submit" class="btn btn-primary form-submit" />
</form>
<table class="table table-responsive">
            <tr>
                <th>Id</th>
                <th>عکس</th>
                <th>نام</th>
                <th>قیمت</th>
                <th>بعد تخفیف</th>
                <th>تعداد</th>
                <th>توضیحات</th>
            </tr>
            @{
                foreach(var item in Model){
                    <tr>
                        <td>@item.Id</td>
                        <td><img style="width: 100px;height:100px" src="@item.picPath" /></td>
                        <td>@item.title</td>
                        <td style="text-decoration: line-through;">@item.price</td>
                        <td><span  style="text-align:center; background-color: red; color: white; font-weight: bold; padding: 4px;border-radius: 7.2px;">@item.offPrice</span></td>
                        <td>@item.count</td>
                        <td>@item.description</td>
                    </tr>
                }
            }
</table>